name: app-deploy
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout lint
        uses: actions/checkout@v3
      - name: use node.js
        uses: actions/setup-node@v3
        with:
        node-version: '20.19'
      - run: npm install
      - run: npm run lint
      - name: checkout build
        uses: actions/checkout@v3
      - name: use node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.19'
      - run: npm install
      - run: npm run build
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout test
        uses: actions/checkout@v3
      - name: use node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.19'
      - run: npm install
      - run: npm run test
  cypress-e2e:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout test cypress-e2e
        uses: actions/checkout@v3
      - name: use node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.19'
      - run: npm install
      - run: npm run test:e2e
